### ISSUE TITLE
accuracy?

### ISSUE THREAD

**Issue by ZHUXUHAN** [gjrb0324/VQA_Baseline_Pytorch#1]
I am concerned about the code you recently released. Can you report the accuracy of your reproduction?

**Comment by gjrb0324** [comment]
The model was trained with MSCOCO VQA1.0 dataset with five epochs training.
Here is the result of my reproduced model: 
![image](https://user-images.githubusercontent.com/48676255/153622580-18c704c8-3b25-4995-b643-93204910f476.png)

I checked every iterations' loss and accuracy.
Every 2K iters in this graph can be considered as each epochs.
